version = 1
SPDX-PackageName = "dde-cooperation"
SPDX-PackageSupplier = "Deepin Technology Co., Ltd."
SPDX-PackageDownloadLocation = "https://github.com/linuxdeepin/dde-cooperation"

[[annotations]]
path = [".github/**", ".obs/**", ".gitlab-ci.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["rpm/**", "debian/**", "archlinux/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["CMakeLists.txt", "**/CMakeLists.txt", "**.cmake", "meson.build", "**/meson.build", ".gitignore", ".clang-format", ".editorconfig"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Deepin Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**.desktop", "**.service", "**.socket", "**.service.in", "**.conf", "**.rules"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.ts"
precedence = "aggregate"
SPDX-FileCopyrightText = "Deepin Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["**.ui", "**.qrc", "**.json", "**.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.png", "**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Deepin Technology Co., Ltd."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**.sh"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
